# Generated by Django 4.1.7 on 2023-05-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_phone_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
