# Generated by Django 4.1.7 on 2023-05-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderplaced_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='total_amount',
        ),
    ]
